version: '3.8'

services:
  app:
    build: .
    container_name: flight-search-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/data/flight_search.db
      JWT_SECRET: mySecretKey123456789012345678901234567890
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
