spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    edu.mit.sidpac.flightsearch: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# JWT Configuration for testing
jwt:
  secret: testSecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 3600000 # 1 hour in milliseconds
  refresh-expiration: 86400000 # 1 day in milliseconds
