spring:
  application:
    name: flight-search-engine
  
  datasource:
    url: jdbc:sqlite:./data/flight_search.db
    driver-class-name: org.sqlite.JDBC
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
    
  sql:
    init:
      mode: never
    
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 8080
  servlet:
    context-path: /


logging:
  level:
    edu.mit.sidpac.flightsearch: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


