spring:
  application:
    name: flight-search-engine
  
  datasource:
    url: jdbc:sqlite:./data/flight_search.db
    driver-class-name: org.sqlite.JDBC
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
    
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true
    
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    edu.mit.sidpac.flightsearch: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
